"""Test project scaffolding (Python equivalent of scaffold.sh).

Manages two modes:
  brownfield — reset prism-test to baseline, preserving .claude/ fixtures
  greenfield — create a fresh isolated temp directory with a minimal project
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Callable


class Scaffold:
    """Manages test project state for the harness."""

    def __init__(
        self,
        prism_test_dir: Path,
        log_info: Callable[[str], None] | None = None,
        log_warn: Callable[[str], None] | None = None,
    ) -> None:
        self.prism_test_dir = prism_test_dir
        self.test_project_dir = prism_test_dir
        self._temp_dirs: list[Path] = []
        self._log_info = log_info or (lambda m: print(f"  INFO  {m}"))
        self._log_warn = log_warn or (lambda m: print(f"  WARN  {m}"))

    def reset(self) -> None:
        """Reset prism-test to harness baseline.

        Removes generated files while preserving .claude/ fixtures and .git/.
        Also removes .prism/ (generated by plugin sessions).
        """
        self.test_project_dir = self.prism_test_dir

        if not (self.prism_test_dir / ".git").is_dir():
            self._log_warn(
                f"scaffold_reset: {self.prism_test_dir} is not a git repo — skipping clean"
            )
            return

        subprocess.run(
            ["git", "clean", "-fd", "--exclude=.claude", "-q"],
            cwd=str(self.prism_test_dir),
            check=False,
            capture_output=True,
        )

        prism_dir = self.prism_test_dir / ".prism"
        if prism_dir.exists():
            shutil.rmtree(prism_dir)

        self._log_info("Scaffold reset: prism-test baseline restored")

    def brownfield(self, git_ref: str = "") -> Path:
        """Use the cultivated prism-test project, reset to baseline first.

        Optionally checks out a specific git ref before running tests.
        Returns the active TEST_PROJECT_DIR.
        """
        self.reset()

        if git_ref and (self.prism_test_dir / ".git").is_dir():
            self._log_info(f"Brownfield: checking out {git_ref} in {self.prism_test_dir}")
            subprocess.run(
                ["git", "checkout", "-q", git_ref],
                cwd=str(self.prism_test_dir),
                check=False,
                capture_output=True,
            )

        self.test_project_dir = self.prism_test_dir
        self._log_info(f"Scaffold brownfield: TEST_PROJECT_DIR={self.test_project_dir}")
        return self.test_project_dir

    def greenfield(self) -> Path:
        """Create a fresh isolated project directory.

        Attempts dotnet new blazor; falls back to a minimal pyproject.toml.
        Returns the new TEST_PROJECT_DIR.
        """
        tmpdir = Path(tempfile.mkdtemp(prefix="prism-harness-greenfield-"))
        self._temp_dirs.append(tmpdir)
        self.test_project_dir = tmpdir

        subprocess.run(["git", "init", "-q", str(tmpdir)], check=False, capture_output=True)
        subprocess.run(
            [
                "git", "commit", "--allow-empty", "-q", "-m", "initial",
                "--author=test <test@harness>",
            ],
            cwd=str(tmpdir),
            check=False,
            capture_output=True,
        )

        if shutil.which("dotnet"):
            self._log_info(f"Greenfield: dotnet blazor in {tmpdir}")
            result = subprocess.run(
                ["dotnet", "new", "blazor", "-o", str(tmpdir), "--force", "-q"],
                capture_output=True,
            )
            if result.returncode != 0:
                self._log_warn("dotnet new blazor failed; using minimal fallback")
                self._create_minimal_project(tmpdir)
        else:
            self._log_info(f"Greenfield: minimal project in {tmpdir} (dotnet not available)")
            self._create_minimal_project(tmpdir)

        self._log_info(f"Scaffold greenfield: TEST_PROJECT_DIR={self.test_project_dir}")
        return self.test_project_dir

    def _create_minimal_project(self, path: Path) -> None:
        (path / "pyproject.toml").write_text(
            '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n'
        )

    def teardown(self) -> None:
        """Remove temp directories created by greenfield()."""
        for d in self._temp_dirs:
            if d.exists() and "prism-harness-greenfield-" in d.name:
                shutil.rmtree(d)
                self._log_info(f"Scaffold teardown: removed {d}")
        self._temp_dirs.clear()
