"""Single source of truth for PRISM's version.

Bump on EVERY commit that changes user-visible behavior. The MAJOR and
MINOR slots gate releases (5.3 = pip + Tauri v6.0.0-dev); the PATCH
slot is incremented on every small iteration so the SPA footer always
identifies exactly which build is live. If you ship a change without
bumping the patch, the user can't tell they got the new code — fix
that habit, not the version number.
"""

PRISM_VERSION = "5.3.14"

# Changelog-ish notes (free-form; keep short)
PRISM_VERSION_NOTES = (
    "v5.3.14: Brain /ask actually returns answers now. v5.3.13 hit "
    "exit_code=1 + empty answer because `allowed_tools=()` doesn't "
    "disable claude's default tool set — claude was calling Grep on "
    "its own to explore the codebase, hit max_turns=3, never emitted "
    "final text. Fix: max_turns=1 (single-shot, no tool iteration "
    "possible) + prompt now explicitly forbids tool calls and instructs "
    "claude to answer from context only. Also fixed source field "
    "mapping (was reading 'file'/'source', actual key is 'source_file'). "
    "v5.3.13: Brain page gains an Ask Claude mode. /api/brain/ask "
    "shells out to the `claude` CLI (claude_cli.invoke, single-shot, "
    "max_turns=3, no allowed_tools) with the question + top-K hybrid "
    "retrieval hits formatted as grounded context. SPA gets a "
    "Search/Ask toggle: same input box, different submit; the answer "
    "renders below with cited sources, duration, output tokens, and "
    "the run_id so the user can audit the call against the Logs tab. "
    "ClaudeCliResult got a final_text() accessor + carries run_id + "
    "duration_s so callers don't have to reimplement extraction. "
    "v5.3.12: Brain page no longer blank. Two fixes: "
    "/api/dashboard/state was hardcoded to /data/projects/<name> (same "
    "docker-path bug we just fixed in /api/graph/summary), so BRAIN "
    "DOCS / ENTITIES / RELATIONSHIPS / COMMUNITIES tiles on the "
    "Dashboard all reported 0 on native. AND BrainService was hitting "
    "'trigger docs_fts_ai already exists' on second init because the "
    "drift timer races with the request-path Brain init (issue #38: "
    "separate connections by design); added IF NOT EXISTS to all "
    "three docs_fts_* trigger CREATEs so the race is harmless. "
    "v5.3.11: /api/graph/summary uses project_data_dir() instead of "
    "the hardcoded /data/projects/<name> docker path, so native "
    "installs see the real entity/relationship/community counts. The "
    "Graph page was reporting 0/0/0 against a graph.db with 2500+ "
    "entities because the API was looking at a file that didn't exist. "
    "v5.3.10: Graph rebuild invokes `python -m graphify` (via "
    "sys.executable) instead of the bare `graphify` console-script. "
    "Pip's editable install puts scripts in a user-site dir that's "
    "frequently not on PATH; the Tauri-spawned daemon was failing "
    "graph.rebuild with WinError 2 because of this. The `-m` path "
    "resolves via Python's own module loader so PATH no longer matters. "
    "v5.3.9: Brain ingest skip list extended to .claude/worktrees/target/"
    ".next/.nuxt/out — folder-mode projects pointing at a repo with "
    "stale worktrees (a common dev pattern) no longer ingest each "
    "worktree as a duplicate copy. Cut a 47k-file walk down to the "
    "actual source. "
    "v5.3.8: Live scan progress bar in Settings → Projects (ScanProgress "
    "component polls /api/jobs scoped to the post-save window) + "
    "onboarding_writer preamble-strip — Claude's CLI prefacing the "
    "markdown with 'I have what I need…' no longer flips the job to "
    "failed. Per-iteration patch-version policy starts here so the "
    "footer always identifies the live build. "
    "v5.3.7: Cancel stale analyzer jobs on source change + clear "
    "post-save notice so rapid folder repointing can't burn Claude "
    "tokens on the abandoned scope. New STATE_CANCELLED + "
    "JobQueue.cancel_stale_pending(sha) called from refresh(). "
    "v5.3.6: Allow Tauri dialog plugin from http://localhost:7778 via "
    "capability remote.urls + no-cache headers on index.html so SPA "
    "rebuilds aren't masked by WebView2 caching the old HTML. "
    "v5.3.5: Native folder picker (tauri-plugin-dialog 'Browse…' "
    "button) for folder-mode projects + Windows Job Object "
    "JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE so Tauri shutdown cascade-kills "
    "the Python child, no more orphan daemons. "
    "v5.3.4: Soft-delete projects (write a .deleted marker, drop from "
    "listing immediately, background sweeper rmtrees once SQLite locks "
    "release) to dodge WinError 32 / WinError 5 on synchronous rmtree "
    "of an in-use project dir. Drift timer also restructured for 5s "
    "stale-Brain release cadence. "
    "v5.3.3: Runtime-aware project config. /api/service-info exposes a "
    "`runtime` field; Settings → Projects uses it to pick docker vs "
    "native copy + placeholder. /api/claude-auth reads the host's "
    "~/.claude on native installs. "
    "v5.3.2: Tauri 2 native shell wraps prism_service. shell spawns "
    "python -m prism_service.cli.prism_cli start with the 8.3 short "
    "path to dodge a Windows msvcrt argv-corruption bug; WebView2 "
    "loads http://localhost:7778. "
    "v5.3.1: Pip distribution baseline (same as v5.3.0 below). "
    "Per-iteration patch policy starts officially at v5.3.8; "
    "5.3.1-5.3.7 are retroactively assigned to commits shipped between "
    "5.3.0 and the policy change. "
    "v5.3.0: Pip distribution. Pivot away from docker-primary. The "
    "Python service moved from `app/` to a proper `prism_service` "
    "package with a pyproject.toml; install via `pip install "
    "prism-service` (or `pipx install prism-service` for isolation). "
    "A new `prism` CLI bundles start/stop/status/logs/update/version "
    "subcommands. Data directory is platform-aware: %LOCALAPPDATA%\\"
    "prism on Windows, ~/.prism on macOS/Linux, honoring PRISM_DATA_DIR "
    "and the legacy /data path when running inside the docker image. "
    "Existing docker users keep working — the docker image still "
    "builds and runs identically; the dist just isn't docker-only "
    "anymore. Sets up the v6.0.0 Tauri shell to spawn `prism start "
    "--daemon` as its child process. "
    "v5.2.5: Fix the ACTUAL /graph palette. v5.2.4 patched "
    "PrismLayerNode and PrismDomainNode (used by /understand LAYERS + "
    "DOMAINS) but missed the Sigma viewer at /graph/viewer/<project> "
    "which is what /graph embeds via iframe. COMMUNITY_COLORS in "
    "graph_static.py was still 13 blue-grey hex codes. Replaced with "
    "16 hue-distinct swatches (8 base hues + 8 lifted variants) "
    "matching the React palette so /understand and /graph share the "
    "same colors for the same meaning. "
    "v5.2.4: Layer + domain graph palette refresh. Both PrismLayerNode "
    "and PrismDomainNode used to keep all swatches inside the cool "
    "blue-grey family, so a 10-layer architecture graph read as one "
    "blob. Replaced with 8 hue-distinct colors (steel, teal, sage, "
    "amber, coral, lavender, rose, warm grey) at muted saturation that "
    "still sits on the Slate Blue dark theme. Domains use the same "
    "hues lifted in lightness so parent cards visually outrank their "
    "child layers. "
    "v5.2.3: GitHub connect off the Connections page entirely. The "
    "Connections section (now `Claude auth` in the sidebar) holds only "
    "Claude OAuth, which IS required. GitHub connect moved into the "
    "project editor and only shows up when you pick `Git URL` mode AND "
    "aren't already authenticated, as a collapsible `Optional: connect "
    "GitHub for private-repo clones + a repo picker` row. Folder-mode "
    "users never see GitHub setup anywhere. "
    "v5.2.2: Settings -> Connections is now honest about what's required "
    "vs optional. Claude OAuth carries a `required` pill (analyzers + Q&A "
    "need it). GitHub carries an `optional` pill plus inline copy saying "
    "you can skip it entirely if you're using folder mode (the v5.2.0 "
    "default) - your host already has git auth and PRISM reads via the "
    "bind-mount. Connect only if you want PRISM to clone private repos "
    "server-side or use the `Browse my repos` picker. "
    "v5.2.1: Fix /understand empty-state. Used to say 'Use Add project in "
    "the top bar' but there is no such button — replaced with a clear "
    "two-mode explainer (Local folder + Git URL) and a `Configure '<name>' "
    "->` button that links straight to Settings -> Projects. Status row "
    "shows `Source folder` for folder-mode projects instead of `Tracked "
    "ref`. "
    "v5.2.0: Local folder mode + host claude auth. Add a project by "
    "pointing at a folder PRISM has bind-mounted from your host (default "
    "`${HOME}/code` → `/code` in the container). No git URL, no clone, "
    "no GitHub credentials in the container — your host already has "
    "your code and your git auth. Settings → Projects has a `Local "
    "folder` / `Git URL` toggle; folder is the new default for new "
    "projects. The host's `~/.claude` is now bind-mounted into the "
    "container, so the container's claude uses your existing logged-in "
    "subscription with no `claude /login` inside the container. The "
    "git-URL clone path (and v5.1.10–11's GitHub OAuth connect) still "
    "work as before for anyone who prefers them. "
    "v5.1.11: GitHub connect is now a one-click button, not a paste-a-PAT "
    "form. The Connections panel walks you through registering a `PRISM` "
    "OAuth App once (deep-link to `github.com/settings/applications/new` "
    "pre-fills the name/URL; flip on `Enable Device Flow`), then `Connect "
    "with GitHub` runs the standard OAuth Device Flow — PRISM hands you "
    "a 6-char code, auto-opens `github.com/login/device`, polls until you "
    "confirm, and stores the resulting access_token at `/data/.git-credentials` "
    "the same way the v5.1.10 PAT path did. Connected state shows your "
    "avatar, login, and scopes instead of a fingerprint. Project source "
    "editor gained a `Browse my repos` button that opens a searchable "
    "list of your GitHub repos and one-clicks the URL + tracked ref into "
    "the form. PAT paste is still available under `Or paste a Personal "
    "Access Token instead →` for anyone who can't register an OAuth app. "
    "Client ID is stored at `/data/.github-client-id` (volume-backed, "
    "chmod 600); env var `PRISM_GITHUB_CLIENT_ID` takes precedence if set. "
    "v5.1.10: GitHub connection lives next to Claude auth in the new "
    "`Connections` sidebar section (renamed from `Claude auth`). Paste "
    "a Personal Access Token, click `Connect`, and PRISM stores it at "
    "`/data/.git-credentials` (volume-backed, chmod 600). Every `git "
    "clone` and `git fetch` PRISM runs picks the token up automatically "
    "via `git -c credential.helper=…`, so the next time you point a "
    "project at a private GitHub repo the clone Just Works. The token "
    "never appears in `understand_state.json`, in logs, or in API "
    "responses — only a `user:•••last4` fingerprint is shown back. "
    "Service tab gained a `GitHub` status row alongside `Claude auth`. "
    "Legacy `/settings/auth` redirects to the new `/settings/connections` "
    "URL so any bookmarks keep working. "
    "v5.1.9: Private-repo clone failures now surface as a clean HTTP "
    "400 from /api/projects and /api/understand/configure instead of "
    "silently creating an unscannable, head-less project. ensure_cloned() "
    "checks the return code of `git clone` and `git fetch`, raises "
    "SourceUnavailable with a credential-scrubbed message (PATs in the "
    "URL are stripped before the error reaches API responses or logs), "
    "and wipes the half-initialized source/ dir so a retry with corrected "
    "credentials starts clean. Customers can pick any credential shape "
    "they want — PAT-in-URL, SSH deploy key + git@ remote, or a "
    "credential helper baked into the container. "
    "v5.1.8: Settings is now a sidebar mode, not a page. Clicking "
    "`Settings` in the footer replaces the left sidebar's Knowledge + "
    "Activity groups with the Settings categories (Projects, Claude "
    "auth, Jobs, Logs, Service). Each routes to /settings/<id> so "
    "deep-links and browser back/forward work. The footer button "
    "flips to `Application` while you're in Settings — single click "
    "back to the main app. Dashboard at the top of the sidebar still "
    "works as a parallel escape hatch. v5.1.7: claude CLI bundled in "
    "image, set-once subscription auth via /data/.claude-config, "
    "DELETE /api/projects, run log + observability, Jobs panel, "
    "scoped --allowedTools, stale-lock recovery, live scan strip, "
    "sidebar pulse while scanning. v5.1.6: bootstrap_after_clone + "
    "drainer + drift UI. v5.1: Understand-Anything. v5.0: "
    "Hermes-native React/Vite SPA."
)
