"""Single source of truth for PRISM's version.

v6.0.0 marks the cutover: native (pip-installed Python service +
Tauri desktop binaries) is now THE primary distribution. Docker
remains supported for server / CI deploys but is no longer the
default install. The 5.3.x patch series was the in-progress
'pip + Tauri v6.0.0-dev' work — that work is now feature-complete
and stable enough to drop the -dev suffix.

Going forward: bump PATCH on every commit that changes user-visible
behavior so the SPA footer always identifies exactly which build is
live. Bump MINOR for backward-compatible feature work, MAJOR for
distribution-shape changes like the docker→native pivot v6 marks.
"""

PRISM_VERSION = "6.0.10"

# Changelog-ish notes (free-form; keep short)
PRISM_VERSION_NOTES = (
    "v6.0.10: Manual reflection trigger closes the loop. New POST "
    "/api/consolidation/run-reflection?candidate_id=X loads the "
    "candidate, builds a single-shot prompt from the prism-reflect "
    "agent guidance + the brief, shells out via claude_cli.invoke "
    "(max_turns=1, allowed_tools=()) for a tokens-cheap headless run, "
    "parses the JSON verdict (strips markdown fences if present), "
    "calls JanitorService.submit, AND iterates verdict.new_memories "
    "calling memory_svc.store for each — because JanitorService.submit "
    "only COUNTS new_memories, it doesn't actually store them (the "
    "LL-08 docstring punts to 'caller wires this up' and the MCP layer "
    "doesn't either). Closing that gap here means a successful "
    "reflection run causes a consolidation_runs row + task_quality_"
    "rollup update + zero-or-more ExpertiseEntry inserts as one atomic-"
    "ish action. The SPA gains a 'Reflect' button on each pending brief "
    "row in /consolidation; click triggers the endpoint, toast reports "
    "duration + memories stored, /memory + /learning fill in real time. "
    "Single-shot variant intentionally — no MCP plumbing, no .mcp.json "
    "routing risk, ~15-30s per run, costs only when YOU click. "
    "v6.0.9: Three concrete wins for 'can I see this actually do "
    "anything': (1) Memory entries become click-to-expand — full "
    "description, id, importance, memory_type, effectiveness (color-"
    "coded green/red), recall count, generation, valid_at, last_recalled, "
    "and evidence dict. The page finally rewards looking at it. "
    "(2) Tasks become click-to-expand with inline status transition "
    "buttons (→ in_progress / → done / → blocked etc.) hitting a new "
    "PATCH /api/tasks/{id} endpoint, plus visible task history (last 5 "
    "transitions). You can now move a task across the kanban from the "
    "SPA without spawning a Claude session. (3) /consolidation gains a "
    "'Background workers' panel honestly listing all 7 daemons in "
    "lifespan (transcript_importer, drift_timer, understand_drainer, "
    "governance_timer, trash_sweeper, auto_updater) — green dots for "
    "running, plus a rose-dot 'reflection_worker NOT RUNNING by design' "
    "entry that explains why /learning stays empty. The panel header "
    "carries a 'Preview next brief' button that calls a new "
    "GET /api/consolidation/next-brief endpoint to show, non-mutatingly, "
    "exactly what the prism-reflect sub-agent would see if invoked: "
    "candidate_id, session_id, trigger, MCPs in the allow-list, and "
    "the full scope_json. Answers 'what would reflection even do' "
    "without spending tokens. "
    "v6.0.8: /memory is no longer dead. Discovered while dogfooding: "
    "PRISM Memory had ZERO entries because Claude Code agents write to "
    "their own auto-memory at ~/.claude/projects/<slug>/memory/*.md "
    "instead of calling mcp__prism__memory_store — two parallel systems "
    "with no bridge. Self-violation of the dogfood-prism rule. Fix: new "
    "POST /api/memory/import-claude-memories walks the project's "
    ".claude memory dir, parses frontmatter (name / description / "
    "metadata.type), maps Claude Code types -> PRISM (type, "
    "classification, memory_type, importance) tuples, and calls "
    "memory_svc.store for each. /memory page gains a page header + "
    "'Import Claude memories' button that triggers it. Idempotent — "
    "re-running supersedes existing entries via the 85%-similarity "
    "dedup, doesn't duplicate. After import: /memory shows 14 entries "
    "across feedback (11) and project (3) domains for this repo, "
    "instead of the empty state that prompted the discovery. "
    "v6.0.7: Memory moved to the Knowledge sidebar group, where it "
    "belongs. v6.0.6 left it in Activity on the rationale that Memory "
    "is both an output of the Learning loop and an input to future "
    "sessions — but that conflates 'data flow role' with 'what kind of "
    "thing it is.' Memory is the persisted record of patterns / "
    "conventions / failures / decisions the team has learned, read by "
    "every future session via memory_recall. That makes it parallel "
    "to Brain (what code exists), Graph (how code connects), and "
    "Understand (architecture) — all four are read surfaces for "
    "accumulated knowledge. Activity now reads cleanly as "
    "things-in-motion: Tasks, Conductor, Retrievals. "
    "v6.0.6: Learning loop is now visible. Three changes addressing "
    "'I have trouble seeing what we are learning even though I know we "
    "have tons of things going on': (1) sidebar regrouped so Sessions, "
    "Consolidation, and Learning sit together as 'Learning loop' in "
    "pipeline order (top-to-bottom = data flow). Memory stays in "
    "Activity because it's both the loop's artifact and the primary "
    "input to every future session. (2) New get_signal_rollup() "
    "aggregates pushbacks / tool_failures / bg_signals / memory_writes "
    "across all consolidation_candidates and counts consolidation_runs "
    "— exposed on /api/consolidation as signal_rollup. (3) /consolidation "
    "renders a headline KPI strip with those counts plus the punchline: "
    "'N signals queued but 0 reflections run — none of this has been "
    "promoted into /memory or scored on /learning.' Makes the gap "
    "between 'extracted' and 'learned' visible at a glance. The "
    "Brief table also now shows per-row signal badges (push / fail / "
    "bg / mem in amber / rose / sky / emerald) and the brief id "
    "becomes a click-to-expand chevron revealing the full "
    "transcript_excerpt that gets shown to the reflection sub-agent. "
    "Pre-v6.0.5 candidates render empty badges and no excerpt — "
    "correct, since they were enqueued before signal extraction "
    "existed. "
    "v6.0.5: Transcript signals -> consolidation pipeline. The disk-"
    "reader (claude_transcripts.import_unseen) was inserting "
    "session_outcomes via raw SQL and silently bypassing the "
    "consolidation bridge — only the MCP-call path "
    "(Brain.record_session_outcome) was enqueuing candidates. As a "
    "result, sessions imported off disk produced metrics but no "
    "reflection input. Two changes: (1) parse_session_metrics now "
    "also extracts a `signals` bucket on the same JSONL walk — "
    "pushbacks (user pushback regex), background-protocol lines "
    "(`result:` / `failed:` / `needs input:` markers from assistant "
    "text), tool failures (tool_result blocks with is_error=true), "
    "and memory-store call sites with 4-message preceding context. "
    "(2) import_unseen now calls enqueue_for_session for every newly "
    "imported session with `trigger='transcript_imported'` and a "
    "scope dict that includes the rendered `transcript_excerpt`. "
    "JanitorService.check already supports transcript_excerpt and "
    "wraps it in <untrusted>…</untrusted> before showing it to the "
    "reflection sub-agent, so the sub-agent finally sees what "
    "actually happened in a session instead of only file/skill/token "
    "counts. Inspired by Redis Iris (launched 2026-05-18) — the right "
    "lesson wasn't 'add vector DB' (PRISM already has BM25 + graph) "
    "but 'stop discarding content during ingestion'. New "
    "tests/unit/test_transcript_signals.py covers parser extraction "
    "(pushback / bg-protocol / tool-failure / memory-store) and the "
    "end-to-end bridge (import_unseen -> consolidation_candidates "
    "with transcript_excerpt in scope_json). "
    "v6.0.4: Dev-mode marker. The Sidebar footer now renders an amber "
    "'DEV' pill next to the version string when the service is started "
    "with PRISM_DEV_MODE=1, so source-run instances (editable pip "
    "install + 8887/8888) are visually distinguishable from a "
    "pipx/Watchtower-managed prod daemon. /api/version gains a "
    "`dev_mode: bool` field driving the pill; defaults false. No "
    "behavior change for prod installs. "
    "v6.0.3: Settings -> Service grows an 'Updates' panel surfacing the "
    "v6.0.1 auto-updater state. Shows running version, latest available, "
    "last check, status pill (up-to-date / update-available / docker / "
    "error). 'Check now' button forces a fresh poll; 'Update to vX.Y.Z' "
    "button triggers download + pip install + re-exec on Linux/Mac (or "
    "surfaces 'restart required' on Windows). Docker installs see the "
    "panel but apply is disabled (Watchtower owns that path). Polls "
    "/api/update/status every 30s so background-check state propagates "
    "into the UI without manual refresh. "
    "v6.0.2: Fix release.yml — `npm ci` was failing because the SPA's "
    "package-lock.json isn't committed. Swapped to `npm install` so "
    "the wheel build can produce web_dist/ on the GitHub Action "
    "runner. Same v6.0.1 auto-update wiring underneath. "
    "v6.0.1: Native auto-update finally works. v6.0.0 shipped the "
    "native install path but left it without a real update mechanism — "
    "the `prism update` CLI was a no-op because prism-service was "
    "never published anywhere pip could pull from. v6.0.1 closes the "
    "gap: release.yml now builds a wheel on every tag push and "
    "attaches it to the GitHub Release. A background poller in the "
    "service hits api.github.com/repos/<owner>/<repo>/releases/latest "
    "every 30 min (PRISM_AUTO_UPDATE_INTERVAL), and when a newer "
    "SemVer tag is found, downloads the wheel + runs "
    "`pip install --upgrade <wheel>` + re-execs the daemon. Docker "
    "installs short-circuit (Watchtower's job). Linux/Mac get clean "
    "in-place upgrade; Windows surfaces 'restart required to apply' "
    "because pip can't replace a running python.exe. New endpoints: "
    "GET /api/update/status, POST /api/update/check, POST "
    "/api/update/apply. Opt-out: PRISM_AUTO_UPDATE=off. "
    "v6.0.0: NATIVE FIRST. The v5.3.x 'pip + Tauri v6.0.0-dev' series "
    "is now stable; this release marks the distribution-shape cutover. "
    "Primary install paths: `pipx install prism-service` for terminal "
    "users on Mac/Linux/Windows, signed Tauri desktop binaries (.dmg "
    "/ .msi / .AppImage) for click-to-run users. Docker image still "
    "ships from GHCR for server / CI deploys but is no longer the "
    "default the docs point at. Host-native auth (~/.claude direct, "
    "host gh CLI + ssh keys for git, host browser for OAuth) means "
    "the docker friction we chased through v5.1 → v5.2 (bind-mount "
    "perms, OAuth localhost redirects, Watchtower update lag) "
    "evaporates on native installs. Also includes the v5.3.25 "
    "/understand contrast pass: UnderstandPage + OnboardingView + "
    "LayersView + DomainsView were dropping AAA semantic text tokens "
    "to opacity-60 sleeves, dropping effective contrast below WCAG "
    "AA — replaced with --text-secondary tokens on body copy. "
    "v5.3.25: /understand contrast pass — "
    "v5.3.24: Version-number cleanup. Regression coverage for "
    "analyzer_runner._strip_preamble_to_heading + _classify (16 unit "
    "tests, originally tagged v5.3.21 in #67) was merged after a "
    "parallel branch had already shipped a different v5.3.21 + v5.3.22 "
    "+ v5.3.23. Bumping past the collision to keep the footer "
    "trustworthy. No logic change beyond the tests already on main. "
    "v5.3.20: Startup hardening. Two regressions that user hit locally "
    "fixed before ship: (1) Brain embedder load is now serialized with "
    "a module-level threading.Lock so concurrent Brain.__init__ from "
    "the drift timer + MCP tools + lifespan can't both race past the "
    "`_MODEL is None` check, both fetch from HuggingFace, and race tqdm's "
    "class state (`'tqdm' object has no attribute '_lock'` → one worker "
    "silently dropped to BM25+GraphRAG only). Also sets "
    "HF_HUB_DISABLE_PROGRESS_BARS=1 and TQDM_DISABLE=1 at brain_engine "
    "import — server processes never show those bars to anyone and they "
    "were the proximate cause of the race. (2) Trash sweeper "
    "`[trash] <name>: still locked, will retry` no longer logs every 30s "
    "for the lifetime of the process. Per-entry attempt counter logs the "
    "warning once on first failure, stays quiet through subsequent "
    "sweeps, and re-logs loudly once at ~1h (PRISM_TRASH_SWEEP_INTERVAL × "
    "120) so the user knows to close the tool still holding the dir. "
    "Successful cleanup after a prior lock logs `cleaned after retry` so "
    "the recovery is visible. New tests/unit/test_trash_sweeper.py and "
    "test_embedder_concurrent_load.py pin both behaviors. "
    "v5.3.19: (skipped, local build) "
    "v5.3.18: (skipped, local build) "
    "v5.3.17: Tauri shell auto-update wired. New "
    ".github/workflows/release-tauri.yml builds signed bundles for "
    "macOS (arm64 + x64), Windows, and Linux on every `v*` tag push, "
    "uploads to GitHub Releases via tauri-apps/tauri-action, and "
    "generates a `latest.json` updater manifest. The shell calls "
    "`updater.check()` on launch (in src/lib.rs setup hook); if the "
    "manifest reports a newer version, Tauri prompts via native "
    "dialog and downloads + installs the signed bundle. Distribution "
    "shape unchanged for docker (GHCR :latest auto-pulled by "
    "Watchtower); Tauri shell now has parity. Manifest verification "
    "uses an embedded minisign pubkey — repo secret "
    "TAURI_SIGNING_PRIVATE_KEY signs the bundles in CI. "
    "v5.3.16: prism_install manifest slimmed from 6 hooks to 3, "
    "matching the v5.3.15 disk-reader. Removed: prism-stop, "
    "prism-subagent, prism-skill-usage, prism-idle-rebuild — all "
    "redundant now that claude_transcripts.import_unseen() populates "
    "session_outcomes + skill_usage natively from "
    "~/.claude/projects/<slug>/*.jsonl. Kept: prism-sync (SessionStart "
    "drift refresh, must fire BEFORE the session), prism-feedback-"
    "signal (PostToolUse retrieval feedback for the Learning page), "
    "prism-edit-learn (PostToolUse Edit/Write — must ingest mid-"
    "session so subsequent brain_searches see the change), prism-"
    "verifier (Stop sensor; project tooling runner, separate from "
    "metrics). Disk-reader extended to populate skill_usage on the "
    "same pass — Sessions AND Skills both flow from the JSONL. "
    "Install instructions now call out the stale-script cleanup so "
    "agents re-running install on a pre-v5.3.16 project can remove "
    "the four orphaned hook files. "
    "v5.3.15: Disk-reader for Claude session transcripts. Claude Code "
    "persists every session as a JSONL at ~/.claude/projects/<slug>/"
    "<uuid>.jsonl. New `claude_transcripts` service walks those, "
    "matches each transcript to a PRISM project by slug prefix, and "
    "inserts any unseen session_id into session_outcomes. Runs on a "
    "60s timer (PRISM_TRANSCRIPT_POLL_S) + manually via POST "
    "/api/sessions/import-transcripts. Cuts the dependency on the Stop "
    "hook (which silently no-ops on Windows when commands say `python3` "
    "— the MS Store stub eats them, no error surfaces). Cross-platform: "
    "uses resolve_claude_home() so it Just Works on Linux / macOS too. "
    "Backfills the user's historical sessions on first run. "
    "Hook audit: of the 6 hooks prism_install ships, 5 are now "
    "redundant (stop, subagent, feedback-signal, skill-usage, "
    "idle-rebuild — all derivable from the JSONL post-hoc). Only "
    "sync (SessionStart prep) + edit-learn (mid-session brain "
    "freshness) need to fire in-line. Next patch will slim the "
    "manifest. "
    "v5.3.14: Brain /ask actually returns answers now. v5.3.13 hit "
    "exit_code=1 + empty answer because `allowed_tools=()` doesn't "
    "disable claude's default tool set — claude was calling Grep on "
    "its own to explore the codebase, hit max_turns=3, never emitted "
    "final text. Fix: max_turns=1 (single-shot, no tool iteration "
    "possible) + prompt now explicitly forbids tool calls and instructs "
    "claude to answer from context only. Also fixed source field "
    "mapping (was reading 'file'/'source', actual key is 'source_file'). "
    "v5.3.13: Brain page gains an Ask Claude mode. /api/brain/ask "
    "shells out to the `claude` CLI (claude_cli.invoke, single-shot, "
    "max_turns=3, no allowed_tools) with the question + top-K hybrid "
    "retrieval hits formatted as grounded context. SPA gets a "
    "Search/Ask toggle: same input box, different submit; the answer "
    "renders below with cited sources, duration, output tokens, and "
    "the run_id so the user can audit the call against the Logs tab. "
    "ClaudeCliResult got a final_text() accessor + carries run_id + "
    "duration_s so callers don't have to reimplement extraction. "
    "v5.3.12: Brain page no longer blank. Two fixes: "
    "/api/dashboard/state was hardcoded to /data/projects/<name> (same "
    "docker-path bug we just fixed in /api/graph/summary), so BRAIN "
    "DOCS / ENTITIES / RELATIONSHIPS / COMMUNITIES tiles on the "
    "Dashboard all reported 0 on native. AND BrainService was hitting "
    "'trigger docs_fts_ai already exists' on second init because the "
    "drift timer races with the request-path Brain init (issue #38: "
    "separate connections by design); added IF NOT EXISTS to all "
    "three docs_fts_* trigger CREATEs so the race is harmless. "
    "v5.3.11: /api/graph/summary uses project_data_dir() instead of "
    "the hardcoded /data/projects/<name> docker path, so native "
    "installs see the real entity/relationship/community counts. The "
    "Graph page was reporting 0/0/0 against a graph.db with 2500+ "
    "entities because the API was looking at a file that didn't exist. "
    "v5.3.10: Graph rebuild invokes `python -m graphify` (via "
    "sys.executable) instead of the bare `graphify` console-script. "
    "Pip's editable install puts scripts in a user-site dir that's "
    "frequently not on PATH; the Tauri-spawned daemon was failing "
    "graph.rebuild with WinError 2 because of this. The `-m` path "
    "resolves via Python's own module loader so PATH no longer matters. "
    "v5.3.9: Brain ingest skip list extended to .claude/worktrees/target/"
    ".next/.nuxt/out — folder-mode projects pointing at a repo with "
    "stale worktrees (a common dev pattern) no longer ingest each "
    "worktree as a duplicate copy. Cut a 47k-file walk down to the "
    "actual source. "
    "v5.3.8: Live scan progress bar in Settings → Projects (ScanProgress "
    "component polls /api/jobs scoped to the post-save window) + "
    "onboarding_writer preamble-strip — Claude's CLI prefacing the "
    "markdown with 'I have what I need…' no longer flips the job to "
    "failed. Per-iteration patch-version policy starts here so the "
    "footer always identifies the live build. "
    "v5.3.7: Cancel stale analyzer jobs on source change + clear "
    "post-save notice so rapid folder repointing can't burn Claude "
    "tokens on the abandoned scope. New STATE_CANCELLED + "
    "JobQueue.cancel_stale_pending(sha) called from refresh(). "
    "v5.3.6: Allow Tauri dialog plugin from http://localhost:7778 via "
    "capability remote.urls + no-cache headers on index.html so SPA "
    "rebuilds aren't masked by WebView2 caching the old HTML. "
    "v5.3.5: Native folder picker (tauri-plugin-dialog 'Browse…' "
    "button) for folder-mode projects + Windows Job Object "
    "JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE so Tauri shutdown cascade-kills "
    "the Python child, no more orphan daemons. "
    "v5.3.4: Soft-delete projects (write a .deleted marker, drop from "
    "listing immediately, background sweeper rmtrees once SQLite locks "
    "release) to dodge WinError 32 / WinError 5 on synchronous rmtree "
    "of an in-use project dir. Drift timer also restructured for 5s "
    "stale-Brain release cadence. "
    "v5.3.3: Runtime-aware project config. /api/service-info exposes a "
    "`runtime` field; Settings → Projects uses it to pick docker vs "
    "native copy + placeholder. /api/claude-auth reads the host's "
    "~/.claude on native installs. "
    "v5.3.2: Tauri 2 native shell wraps prism_service. shell spawns "
    "python -m prism_service.cli.prism_cli start with the 8.3 short "
    "path to dodge a Windows msvcrt argv-corruption bug; WebView2 "
    "loads http://localhost:7778. "
    "v5.3.1: Pip distribution baseline (same as v5.3.0 below). "
    "Per-iteration patch policy starts officially at v5.3.8; "
    "5.3.1-5.3.7 are retroactively assigned to commits shipped between "
    "5.3.0 and the policy change. "
    "v5.3.0: Pip distribution. Pivot away from docker-primary. The "
    "Python service moved from `app/` to a proper `prism_service` "
    "package with a pyproject.toml; install via `pip install "
    "prism-service` (or `pipx install prism-service` for isolation). "
    "A new `prism` CLI bundles start/stop/status/logs/update/version "
    "subcommands. Data directory is platform-aware: %LOCALAPPDATA%\\"
    "prism on Windows, ~/.prism on macOS/Linux, honoring PRISM_DATA_DIR "
    "and the legacy /data path when running inside the docker image. "
    "Existing docker users keep working — the docker image still "
    "builds and runs identically; the dist just isn't docker-only "
    "anymore. Sets up the v6.0.0 Tauri shell to spawn `prism start "
    "--daemon` as its child process. "
    "v5.2.5: Fix the ACTUAL /graph palette. v5.2.4 patched "
    "PrismLayerNode and PrismDomainNode (used by /understand LAYERS + "
    "DOMAINS) but missed the Sigma viewer at /graph/viewer/<project> "
    "which is what /graph embeds via iframe. COMMUNITY_COLORS in "
    "graph_static.py was still 13 blue-grey hex codes. Replaced with "
    "16 hue-distinct swatches (8 base hues + 8 lifted variants) "
    "matching the React palette so /understand and /graph share the "
    "same colors for the same meaning. "
    "v5.2.4: Layer + domain graph palette refresh. Both PrismLayerNode "
    "and PrismDomainNode used to keep all swatches inside the cool "
    "blue-grey family, so a 10-layer architecture graph read as one "
    "blob. Replaced with 8 hue-distinct colors (steel, teal, sage, "
    "amber, coral, lavender, rose, warm grey) at muted saturation that "
    "still sits on the Slate Blue dark theme. Domains use the same "
    "hues lifted in lightness so parent cards visually outrank their "
    "child layers. "
    "v5.2.3: GitHub connect off the Connections page entirely. The "
    "Connections section (now `Claude auth` in the sidebar) holds only "
    "Claude OAuth, which IS required. GitHub connect moved into the "
    "project editor and only shows up when you pick `Git URL` mode AND "
    "aren't already authenticated, as a collapsible `Optional: connect "
    "GitHub for private-repo clones + a repo picker` row. Folder-mode "
    "users never see GitHub setup anywhere. "
    "v5.2.2: Settings -> Connections is now honest about what's required "
    "vs optional. Claude OAuth carries a `required` pill (analyzers + Q&A "
    "need it). GitHub carries an `optional` pill plus inline copy saying "
    "you can skip it entirely if you're using folder mode (the v5.2.0 "
    "default) - your host already has git auth and PRISM reads via the "
    "bind-mount. Connect only if you want PRISM to clone private repos "
    "server-side or use the `Browse my repos` picker. "
    "v5.2.1: Fix /understand empty-state. Used to say 'Use Add project in "
    "the top bar' but there is no such button — replaced with a clear "
    "two-mode explainer (Local folder + Git URL) and a `Configure '<name>' "
    "->` button that links straight to Settings -> Projects. Status row "
    "shows `Source folder` for folder-mode projects instead of `Tracked "
    "ref`. "
    "v5.2.0: Local folder mode + host claude auth. Add a project by "
    "pointing at a folder PRISM has bind-mounted from your host (default "
    "`${HOME}/code` → `/code` in the container). No git URL, no clone, "
    "no GitHub credentials in the container — your host already has "
    "your code and your git auth. Settings → Projects has a `Local "
    "folder` / `Git URL` toggle; folder is the new default for new "
    "projects. The host's `~/.claude` is now bind-mounted into the "
    "container, so the container's claude uses your existing logged-in "
    "subscription with no `claude /login` inside the container. The "
    "git-URL clone path (and v5.1.10–11's GitHub OAuth connect) still "
    "work as before for anyone who prefers them. "
    "v5.1.11: GitHub connect is now a one-click button, not a paste-a-PAT "
    "form. The Connections panel walks you through registering a `PRISM` "
    "OAuth App once (deep-link to `github.com/settings/applications/new` "
    "pre-fills the name/URL; flip on `Enable Device Flow`), then `Connect "
    "with GitHub` runs the standard OAuth Device Flow — PRISM hands you "
    "a 6-char code, auto-opens `github.com/login/device`, polls until you "
    "confirm, and stores the resulting access_token at `/data/.git-credentials` "
    "the same way the v5.1.10 PAT path did. Connected state shows your "
    "avatar, login, and scopes instead of a fingerprint. Project source "
    "editor gained a `Browse my repos` button that opens a searchable "
    "list of your GitHub repos and one-clicks the URL + tracked ref into "
    "the form. PAT paste is still available under `Or paste a Personal "
    "Access Token instead →` for anyone who can't register an OAuth app. "
    "Client ID is stored at `/data/.github-client-id` (volume-backed, "
    "chmod 600); env var `PRISM_GITHUB_CLIENT_ID` takes precedence if set. "
    "v5.1.10: GitHub connection lives next to Claude auth in the new "
    "`Connections` sidebar section (renamed from `Claude auth`). Paste "
    "a Personal Access Token, click `Connect`, and PRISM stores it at "
    "`/data/.git-credentials` (volume-backed, chmod 600). Every `git "
    "clone` and `git fetch` PRISM runs picks the token up automatically "
    "via `git -c credential.helper=…`, so the next time you point a "
    "project at a private GitHub repo the clone Just Works. The token "
    "never appears in `understand_state.json`, in logs, or in API "
    "responses — only a `user:•••last4` fingerprint is shown back. "
    "Service tab gained a `GitHub` status row alongside `Claude auth`. "
    "Legacy `/settings/auth` redirects to the new `/settings/connections` "
    "URL so any bookmarks keep working. "
    "v5.1.9: Private-repo clone failures now surface as a clean HTTP "
    "400 from /api/projects and /api/understand/configure instead of "
    "silently creating an unscannable, head-less project. ensure_cloned() "
    "checks the return code of `git clone` and `git fetch`, raises "
    "SourceUnavailable with a credential-scrubbed message (PATs in the "
    "URL are stripped before the error reaches API responses or logs), "
    "and wipes the half-initialized source/ dir so a retry with corrected "
    "credentials starts clean. Customers can pick any credential shape "
    "they want — PAT-in-URL, SSH deploy key + git@ remote, or a "
    "credential helper baked into the container. "
    "v5.1.8: Settings is now a sidebar mode, not a page. Clicking "
    "`Settings` in the footer replaces the left sidebar's Knowledge + "
    "Activity groups with the Settings categories (Projects, Claude "
    "auth, Jobs, Logs, Service). Each routes to /settings/<id> so "
    "deep-links and browser back/forward work. The footer button "
    "flips to `Application` while you're in Settings — single click "
    "back to the main app. Dashboard at the top of the sidebar still "
    "works as a parallel escape hatch. v5.1.7: claude CLI bundled in "
    "image, set-once subscription auth via /data/.claude-config, "
    "DELETE /api/projects, run log + observability, Jobs panel, "
    "scoped --allowedTools, stale-lock recovery, live scan strip, "
    "sidebar pulse while scanning. v5.1.6: bootstrap_after_clone + "
    "drainer + drift UI. v5.1: Understand-Anything. v5.0: "
    "Hermes-native React/Vite SPA."
)
