"""Regression test generated by law_promotion._install_rule() the
moment the promoted rule 'models-must-not-depend-on-services' first proved itself: it fired on its
own violating fixture and stayed quiet on its own compliant one. This
file is SELF-CONTAINED -- the rule's own TTL and both fixtures are
embedded below as string literals, not read from promoted-shapes.ttl at
test time, so this stays a valid regression check even if that file's
format or location ever changes.

Owner ask (2026-08-27): "the ontology should work with the code and the
rules to ensure that rules are covered by unit/int tests... tied back to
the code, and that is where the ontology overlaps."
"""

from __future__ import annotations

import shutil
import uuid

import rdflib

RULE_NAME = 'models-must-not-depend-on-services'

RULE_TTL = '@prefix o: <urn:prism:onto:> .\n@prefix sh: <http://www.w3.org/ns/shacl#> .\n@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n\no:models-must-not-depend-on-services.target a sh:NodeShape ;\n    sh:targetClass o:Module ;\n    sh:sparql o:models-must-not-depend-on-services .\n\no:models-must-not-depend-on-services a sh:SPARQLConstraint ;\n    rdfs:comment "domain dataclasses stay dependency-free (models/*.py import nothing from services/)" ;\n    sh:name "models must not depend on services" ;\n    sh:description "domain dataclasses stay dependency-free (models/*.py import nothing from services/)" ;\n    sh:message "a module under models imports a module under services" ;\n    o:derivedFrom <urn:prism:onto:instance/memory/mx-6320ab> ;\n    sh:select """\n        PREFIX o: <urn:prism:onto:>\n        SELECT $this WHERE {\n            $this a o:Module ; o:imports ?m .\n            $this rdfs:label ?fromPath .\n            ?m rdfs:label ?toPath .\n            FILTER(STRSTARTS(?fromPath, "models") && STRSTARTS(?toPath, "services"))\n        }\n    """ .\n'

VIOLATING_FIXTURE = '@prefix o: <urn:prism:onto:> .\n@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\no:mod-models-bad-py a o:Module ; rdfs:label "models/bad.py" ; o:imports o:mod-services-thing-py .\no:mod-services-thing-py a o:Module ; rdfs:label "services/thing.py" .\n'

COMPLIANT_FIXTURE = '@prefix o: <urn:prism:onto:> .\n@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\no:mod-models-ok-py a o:Module ; rdfs:label "models/ok.py" ; o:imports o:mod-models-sibling-py .\no:mod-models-sibling-py a o:Module ; rdfs:label "models/sibling.py" .\n'

_SHAPES_HEADER = """@prefix o: <urn:prism:onto:> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
"""


def test_models_must_not_depend_on_services_fires_on_violating_and_stays_quiet_on_compliant():
    from prism_service.config import project_data_dir
    from prism_service.services import ontology_rules
    from prism_service.services.ontology_graph import NS, OntologyGraph

    project = "law-verify-" + RULE_NAME[:24] + "-" + uuid.uuid4().hex[:8]
    path = project_data_dir(project) / "ontology" / "promoted-shapes.ttl"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_SHAPES_HEADER + "\n" + RULE_TTL.strip() + "\n",
                     encoding="utf-8")
    try:
        tbox = OntologyGraph(project).to_rdflib()

        violating_graph = rdflib.Graph()
        violating_graph += tbox
        violating_graph.parse(data=VIOLATING_FIXTURE, format="turtle",
                              publicID=NS)
        _inferred, violations = ontology_rules.run_shapes(
            violating_graph, project)
        assert RULE_NAME in violations, (
            RULE_NAME, list(violations),
            "the promoted rule did not fire on its own violating fixture")

        if COMPLIANT_FIXTURE.strip():
            compliant_graph = rdflib.Graph()
            compliant_graph += tbox
            compliant_graph.parse(data=COMPLIANT_FIXTURE, format="turtle",
                                  publicID=NS)
            _inferred2, quiet = ontology_rules.run_shapes(
                compliant_graph, project)
            assert RULE_NAME not in quiet, (
                RULE_NAME, list(quiet),
                "the promoted rule fired on its own compliant fixture")
    finally:
        shutil.rmtree(project_data_dir(project), ignore_errors=True)
